<?xml version="1.0" encoding="utf-8"?>
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
	<PumaInstallRoot>$(UserProfile)\Puma</PumaInstallRoot>
	<PumaLibDir>$(PumaInstallRoot)\lib\$(Platform)\$(Configuration)\</PumaLibDir>
	<PumaIncludeDir>$(PumaInstallRoot)\include\</PumaIncludeDir>
	<OutDir>$(PumaLibDir)</OutDir>
  </PropertyGroup>
</Project>
